import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { ACHIEVEMENT_KEYS } from "@factions/domain";

/**
 * Reads the glyph path of every badge SVG in public/achievements/svg/ and
 * writes lib/achievement-glyphs.ts, so <AchievementBadge> draws the glyph
 * inline with no fetch and no SVG parsing at request time. Runs as the web
 * app's `prebuild`; the output is committed, and test/achievement-glyphs.test.ts
 * fails when the SVGs and the module disagree.
 *
 * ⚠️ One key per SVG, and every key from @factions/domain: a badge without a
 * glyph would draw an empty shield, so a missing or extra file exits 1.
 */
const web = join(import.meta.dirname, "..");
const svgDir = join(web, "public", "achievements", "svg");
const out = join(web, "lib", "achievement-glyphs.ts");

/** The glyph is the path inside the `translate(17 15) scale(1.25)` group; the first path is the shield. */
const GLYPH = /<g transform="translate\(17 15\) scale\(1\.25\)"><path d="([^"]+)"/u;

export function glyphOf(svg: string, key: string): string {
  const d = GLYPH.exec(svg)?.[1];
  if (!d) throw new Error(`${key}.svg: no glyph path inside the translate(17 15) scale(1.25) group`);
  return d;
}

export function renderModule(glyphs: Record<string, string>): string {
  const lines = Object.entries(glyphs).map(([k, d]) => `  ${k}: ${JSON.stringify(d)},`);
  return [
    "// Generated by scripts/build-achievement-glyphs.ts from public/achievements/svg/*.svg — do not edit.",
    'import type { AchievementKey } from "@factions/domain";',
    "",
    "/** The glyph path of every badge, in the SVGs' 24×24 space (drawn under translate(17 15) scale(1.25)). */",
    "export const ACHIEVEMENT_GLYPHS: Record<AchievementKey, string> = {",
    ...lines,
    "};",
    "",
  ].join("\n");
}

export function build(): string {
  const glyphs: Record<string, string> = {};
  for (const key of ACHIEVEMENT_KEYS) glyphs[key] = glyphOf(readFileSync(join(svgDir, `${key}.svg`), "utf8"), key);
  return renderModule(glyphs);
}

if (process.argv[1] && import.meta.url === new URL(`file://${process.argv[1]}`).href) {
  writeFileSync(out, build());
  console.log(`wrote ${out} (${ACHIEVEMENT_KEYS.length} glyphs)`);
}
