export type EventType =
  | "flag.raised"
  | "flag.lowered"
  | "flagpole.placed"
  | "flagpole.folded"
  | "flagpole.built"
  | "flagpole.dismantled"
  | "base.built"
  | "base.dismantled"
  | "player.position"
  | "emote.performed"
  | "player.connected"
  | "player.disconnected"
  | "player.killed"
  | "player.died"
  | "player.teleported";
