/**
 * Where each item's committed thumbnail came from.
 *
 * ⚠️ The wikis name files after the in-game DISPLAY name, often adjective
 * first, so essentially nothing maps by rule from a class name:
 *   HunterPants_Autumn  -> AutumnHunterPants.png
 *   AliceBag_Black      -> ALICE Backpack Black.png
 *   HuntingBag_Hannah   -> HannahsBackpack.png
 * This table is the complete, explicit answer, the same shape and for the same
 * reason as flag-images.ts's WIKI_FILENAME. Every entry was reviewed by hand.
 *
 * ⚠️ `wiki: "supplied"` means a URL given by hand because both wikis were
 * wrong; `wiki: "local"` means the image was trimmed out of a photo and has no
 * wiki source to re-fetch. Neither can be refreshed by the fetch script
 * without a human.
 */
export const WIKI_FILENAME: Readonly<Record<string, { file: string; wiki: string }>> = {
  AliceBag_Black: { file: "ALICE Backpack Black.png", wiki: "wiki.gg" },
  AliceBag_Camo: { file: "AliceBackpack Camo.png", wiki: "wiki.gg" },
  AliceBag_Green: { file: "AliceBackpack Green.png", wiki: "wiki.gg" },
  Attack2Bag_Black: { file: "Attack2Bag Black.png", wiki: "wiki.gg" },
  Attack2Bag_Green: { file: "Attack2Bag Green.png", wiki: "wiki.gg" },
  Attack2Bag_Ttsko: { file: "Attack2Bag Ttsko.png", wiki: "wiki.gg" },
  Attack2Bag_Yeger: { file: "Attack2Bag Yeger.png", wiki: "wiki.gg" },
  AviatorGlasses: { file: "Rocket Aviators.png", wiki: "wiki.gg" },
  BDUJacket: { file: "BDUJacket.png", wiki: "wiki.gg" },
  BDUPants: { file: "BDU_Pants_Model.png", wiki: "wiki.gg" },
  Balaclava3Holes_White: { file: "Balaclava3Holes White.png", wiki: "wiki.gg" },
  BalaclavaMask_BDU: { file: "BalaclavaMask BDU.png", wiki: "wiki.gg" },
  BalaclavaMask_Beige: { file: "BalaclavaBeige.png", wiki: "wiki.gg" },
  BalaclavaMask_Black: { file: "BalaclavaBlack.png", wiki: "wiki.gg" },
  BalaclavaMask_Blackskull: { file: "Balaclava.png", wiki: "wiki.gg" },
  BalaclavaMask_Blue: { file: "BalaclavaBlueDamaged.png", wiki: "wiki.gg" },
  BalaclavaMask_Chain: { file: "BalaclavaMask Chain.png", wiki: "wiki.gg" },
  BalaclavaMask_Green: { file: "https://db.mydayz.eu/wp-content/uploads/2025/08/BalaclavaMask_Green.png.webp", wiki: "supplied" },
  BalaclavaMask_Pig: { file: "BalaclavaMask Pig.png", wiki: "wiki.gg" },
  BalaclavaMask_Pink: { file: "BalaclavaPink.png", wiki: "wiki.gg" },
  BalaclavaMask_White: { file: "BalaclavaWhite.png", wiki: "wiki.gg" },
  Bandana_Blackpattern: { file: "BandanaBlackPattern.png", wiki: "wiki.gg" },
  Bandana_Camopattern: { file: "BandanaCamoPattern.png", wiki: "wiki.gg" },
  Bandana_Greenpattern: { file: "BandanaGreenPattern.png", wiki: "wiki.gg" },
  Bandana_Polkapattern: { file: "BandanaPolkaDot.png", wiki: "wiki.gg" },
  Bandana_Redpattern: { file: "BandanaRedPattern.png", wiki: "wiki.gg" },
  BomberJacket_Black: { file: "BomberJacket Black.png", wiki: "wiki.gg" },
  BomberJacket_Blue: { file: "Item Bomber Jacket BLUE.png", wiki: "wiki.gg" },
  BomberJacket_Brown: { file: "BomberJacket Brown.png", wiki: "wiki.gg" },
  BomberJacket_Grey: { file: "Bomber Jacket Grey.png", wiki: "wiki.gg" },
  BomberJacket_Maroon: { file: "BomberJacket Maroon.png", wiki: "wiki.gg" },
  BomberJacket_Olive: { file: "BomberJacket Olive.png", wiki: "wiki.gg" },
  BomberJacket_SkyBlue: { file: "BomberJacketLightBlue.png", wiki: "wiki.gg" },
  BushlatPoliceJacket_Blue: { file: "BushlatPoliceJacket Blue.png", wiki: "wiki.gg" },
  CargoPants_Beige: { file: "BeigeCargoPants.png", wiki: "wiki.gg" },
  CargoPants_Black: { file: "CargoPantsBlack.png", wiki: "wiki.gg" },
  CargoPants_Blue: { file: "CargoPantsBlue.png", wiki: "wiki.gg" },
  CargoPants_Green: { file: "CargoPantsGreen.png", wiki: "wiki.gg" },
  CargoPants_Grey: { file: "CargoPantsGrey.png", wiki: "wiki.gg" },
  ChristmasHeadband_Antlers: { file: "ChristmasHeadband Antlers.png", wiki: "wiki.gg" },
  ChristmasHeadband_Gingerbread: { file: "ChristmasHeadband Gingerbread.png", wiki: "wiki.gg" },
  ChristmasHeadband_Trees: { file: "ChristmasHeadband Trees.png", wiki: "wiki.gg" },
  ColdOperationBoots_Camo: { file: "ColdOperationBoots Camo.png", wiki: "wiki.gg" },
  ColdOperationBoots_Green: { file: "ColdOperationBoots Green.png", wiki: "wiki.gg" },
  ColdOperationBoots_Grey: { file: "ColdOperationBoots Grey.png", wiki: "wiki.gg" },
  CombatBoots_Beige: { file: "CombatBootsBeige.png", wiki: "wiki.gg" },
  CombatBoots_Black: { file: "CombatBootsBlack.png", wiki: "wiki.gg" },
  CombatBoots_Brown: { file: "CombatBootsBrown.png", wiki: "wiki.gg" },
  CombatBoots_Green: { file: "CombatBootsGreen.png", wiki: "wiki.gg" },
  CombatBoots_Grey: { file: "CombatBootsGrey.png", wiki: "wiki.gg" },
  CowboyHat_Brown: { file: "Cowboy Hat Brown.png", wiki: "wiki.gg" },
  CowboyHat_black: { file: "Cowboy Hat Black 2.png", wiki: "wiki.gg" },
  CowboyHat_darkBrown: { file: "CowboyHat DarkBrown.png", wiki: "wiki.gg" },
  CowboyHat_green: { file: "Cowboy hat pristine(green).png", wiki: "wiki.gg" },
  CoyoteBag_Brown: { file: "CoyoteBackpack Brown.png", wiki: "wiki.gg" },
  CoyoteBag_Green: { file: "CoyoteBackpack Green.png", wiki: "wiki.gg" },
  CoyoteBag_Winter: { file: "CoyoteBag Winter.png", wiki: "wiki.gg" },
  DesignerGlasses: { file: "Designer Sunglasses New.png", wiki: "wiki.gg" },
  DownJacket_Blue: { file: "DownJacketBlue.png", wiki: "wiki.gg" },
  DownJacket_Green: { file: "DownJacketGreen.png", wiki: "wiki.gg" },
  DownJacket_Orange: { file: "DownJacketOrange.png", wiki: "wiki.gg" },
  DownJacket_Red: { file: "DownJacketRed.png", wiki: "wiki.gg" },
  EyeMask_Black: { file: "CarnivalMask Black.png", wiki: "wiki.gg" },
  EyeMask_Blue: { file: "CarnivalMask Blue.png", wiki: "wiki.gg" },
  EyeMask_Christmas: { file: "CarnivalMask Christmas.png", wiki: "wiki.gg" },
  EyeMask_Dead: { file: "CarnivalMask Dead.png", wiki: "wiki.gg" },
  EyeMask_NewYears: { file: "CarnivalMask NewYears.png", wiki: "wiki.gg" },
  EyeMask_Red: { file: "CarnivalMask Red.png", wiki: "wiki.gg" },
  EyeMask_Valentines: { file: "CarnivalMask Valentines.png", wiki: "wiki.gg" },
  EyeMask_Yellow: { file: "CarnivalMask Yellow.png", wiki: "wiki.gg" },
  GorkaEJacket_Autumn: { file: "GorkaEJacket Autumn.png", wiki: "wiki.gg" },
  GorkaEJacket_Flat: { file: "GorkaEJacket Flat.png", wiki: "wiki.gg" },
  GorkaEJacket_PautRev: { file: "GorkaEJacket PautRev.png", wiki: "wiki.gg" },
  GorkaEJacket_Summer: { file: "GorkaEJacket Summer.png", wiki: "wiki.gg" },
  GorkaEJacket_Winter: { file: "GorkaEJacket Winter.png", wiki: "wiki.gg" },
  GorkaPants_Autumn: { file: "GorkaMilitaryPantsAutumn.png", wiki: "wiki.gg" },
  GorkaPants_Flat: { file: "GorkaMilitaryPantsFlat.png", wiki: "wiki.gg" },
  GorkaPants_PautRev: { file: "GorkaMilitaryPantsPautRev.png", wiki: "wiki.gg" },
  GorkaPants_Summer: { file: "GorkaPants Summer.png", wiki: "wiki.gg" },
  GorkaPants_Winter: { file: "GorkaPants Winter.png", wiki: "wiki.gg" },
  Headdress_Bear: { file: "Headdress Bear.png", wiki: "wiki.gg" },
  Headdress_Fox: { file: "Headdress Fox.png", wiki: "wiki.gg" },
  Headdress_Wolf: { file: "Headdress Wolf.png", wiki: "wiki.gg" },
  HikingJacket_Black: { file: "HikingJacket BlackBlue Model.png", wiki: "wiki.gg" },
  HikingJacket_Blue: { file: "HikingJacket Blue Model.png", wiki: "wiki.gg" },
  HikingJacket_Green: { file: "HikingJacket Green Model.png", wiki: "wiki.gg" },
  HikingJacket_Red: { file: "HikingJacket BlackRed Model.png", wiki: "wiki.gg" },
  HipPack_Black: { file: "HipPack Black.png", wiki: "wiki.gg" },
  HipPack_Green: { file: "HipPack Green.png", wiki: "wiki.gg" },
  HipPack_Medical: { file: "HipPack Medical.png", wiki: "wiki.gg" },
  HipPack_Party: { file: "HipPack Party.png", wiki: "wiki.gg" },
  HockeyMask: { file: "Hockey Mask 2.png", wiki: "wiki.gg" },
  HunterPants_Autumn: { file: "AutumnHunterPants.png", wiki: "wiki.gg" },
  HunterPants_Brown: { file: "BrownHunterPants.png", wiki: "wiki.gg" },
  HunterPants_Spring: { file: "SpringHunterPants.png", wiki: "wiki.gg" },
  HunterPants_Summer: { file: "SummerHunterPants.png", wiki: "wiki.gg" },
  HunterPants_Winter: { file: "WinterHunterPants.png", wiki: "wiki.gg" },
  HuntingBag: { file: "Hunting Backpack.png", wiki: "wiki.gg" },
  HuntingBag_Hannah: { file: "HannahsBackpack.png", wiki: "wiki.gg" },
  HuntingJacket_Autumn: { file: "HunterJacket Autumn.png", wiki: "wiki.gg" },
  HuntingJacket_Brown: { file: "HunterJacket Brown.png", wiki: "wiki.gg" },
  HuntingJacket_Spring: { file: "HuntingJacket Spring.png", wiki: "wiki.gg" },
  HuntingJacket_Summer: { file: "HunterJacket Summer.png", wiki: "wiki.gg" },
  HuntingJacket_Winter: { file: "HunterJacket Winter.png", wiki: "wiki.gg" },
  JungleBoots_Beige: { file: "JungleBootsBeige.png", wiki: "wiki.gg" },
  JungleBoots_Black: { file: "JungleBootsBlack.png", wiki: "wiki.gg" },
  JungleBoots_Brown: { file: "JungleBootsBrown.png", wiki: "wiki.gg" },
  JungleBoots_Green: { file: "JungleBootsGreen.png", wiki: "wiki.gg" },
  JungleBoots_Olive: { file: "Jungle Boots Olive.png", wiki: "wiki.gg" },
  LeafCrown_Autumn: { file: "LeafCrown Autumn.png", wiki: "wiki.gg" },
  LeafCrown_Spring: { file: "LeafCrown Spring.png", wiki: "wiki.gg" },
  LeafCrown_Summer: { file: "LeafCrown Summer.png", wiki: "wiki.gg" },
  LeafCrown_Winter: { file: "LeafCrown Winter.png", wiki: "wiki.gg" },
  M65Jacket_Black: { file: "M65Jacket Black.png", wiki: "wiki.gg" },
  M65Jacket_Khaki: { file: "M65Jacket Khaki.png", wiki: "wiki.gg" },
  M65Jacket_Olive: { file: "M65FieldJacketOlive.png", wiki: "wiki.gg" },
  M65Jacket_Tan: { file: "M65Jacket Tan.png", wiki: "wiki.gg" },
  MilitaryBoots_Beige: { file: "MilitaryBootsBeige.png", wiki: "wiki.gg" },
  MilitaryBoots_Black: { file: "MilitaryBootsBlack.png", wiki: "wiki.gg" },
  MilitaryBoots_Bluerock: { file: "MilitaryBootsBluerock.png", wiki: "wiki.gg" },
  MilitaryBoots_Brown: { file: "MilitaryBootsBrown.png", wiki: "wiki.gg" },
  MilitaryBoots_Redpunk: { file: "MilitaryBootsRedpunk.png", wiki: "wiki.gg" },
  MilitaryCap_BDU: { file: "MilitaryCap BDU.png", wiki: "wiki.gg" },
  MilitaryCap_Desert: { file: "MilitaryCap Desert.png", wiki: "wiki.gg" },
  MilitaryCap_Woodland: { file: "MilitaryCap Woodland.png", wiki: "wiki.gg" },
  MimeMask_Female: { file: "MimeMask Female.png", wiki: "wiki.gg" },
  MimeMask_Male: { file: "MimeMask Male.png", wiki: "wiki.gg" },
  MorozkoHat: { file: "MorozkoHat.png", wiki: "wiki.gg" },
  NavyUniformJacket: { file: "NavyUniformJacket.png", wiki: "wiki.gg" },
  NavyUniformPants: { file: "NavyUniformPants.png", wiki: "wiki.gg" },
  OMKJacket_Navy: { file: "OMKJacket Navy.png", wiki: "wiki.gg" },
  OMKPants_Navy: { file: "OMKPants Navy.png", wiki: "wiki.gg" },
  OMNOGloves_Brown: { file: "Combat Gloves Brown.png", wiki: "fandom" },
  OMNOGloves_Gray: { file: "Combat Gloves Gray.png", wiki: "fandom" },
  PaddedGloves_Beige: { file: "PaddedGloves Beige.png", wiki: "wiki.gg" },
  PaddedGloves_Brown: { file: "PaddedGloves Brown.png", wiki: "wiki.gg" },
  PaddedGloves_Threat: { file: "PaddedGloves Threat.png", wiki: "wiki.gg" },
  PaydayMask_Chains: { file: "PaydayMask Chains.png", wiki: "wiki.gg" },
  PaydayMask_Dallas: { file: "PaydayMask Dallas.png", wiki: "wiki.gg" },
  PaydayMask_Hoxton: { file: "PaydayMask Hoxton.png", wiki: "wiki.gg" },
  PaydayMask_Wolf: { file: "PaydayMask Wolf.png", wiki: "wiki.gg" },
  PilotJacket_Black: { file: "PilotJacket Black.png", wiki: "wiki.gg" },
  PilotJacket_Brown: { file: "PilotJacket Brown.png", wiki: "wiki.gg" },
  PilotJacket_Yellow: { file: "PilotJacket Yellow.png", wiki: "wiki.gg" },
  QuiltedJacket_Black: { file: "QuiltedJacketBlack.png", wiki: "wiki.gg" },
  QuiltedJacket_Blue: { file: "QuiltedJacketBlue.png", wiki: "wiki.gg" },
  QuiltedJacket_Green: { file: "QuiltedJacketGreen.png", wiki: "wiki.gg" },
  QuiltedJacket_Grey: { file: "QuiltedJacketGrey.png", wiki: "wiki.gg" },
  QuiltedJacket_Orange: { file: "QuiltedJacketOrange.png", wiki: "wiki.gg" },
  QuiltedJacket_Red: { file: "QuiltedJacketRed.png", wiki: "wiki.gg" },
  QuiltedJacket_Violet: { file: "QuiltedJacketViolet.png", wiki: "wiki.gg" },
  QuiltedJacket_Yellow: { file: "QuiltedJacketYellow.png", wiki: "wiki.gg" },
  RidersJacket_Black: { file: "RidersJacket Black.png", wiki: "wiki.gg" },
  SantasBeard: { file: "SantasBeard.png", wiki: "wiki.gg" },
  SantasHat: { file: "SantasHat.png", wiki: "wiki.gg" },
  SkiGloves_90s: { file: "SkiGloves 90s.png", wiki: "wiki.gg" },
  SkiGloves_Blue: { file: "SkiGloves Blue.png", wiki: "wiki.gg" },
  SkiGloves_Red: { file: "SkiGloves Red.png", wiki: "wiki.gg" },
  SkiGoggles_BlackYellow: { file: "SkiGoggles BlackYellow.png", wiki: "wiki.gg" },
  SkiGoggles_WhiteClear: { file: "SkiGoggles WhiteClear.png", wiki: "wiki.gg" },
  SkiGoggles_WhiteDark: { file: "SkiGoggles WhiteDark.png", wiki: "wiki.gg" },
  SportGlasses_Black: { file: "Athletic Sunglasses Black.png", wiki: "wiki.gg" },
  SportGlasses_Blue: { file: "JoeyXsunglasses.png", wiki: "wiki.gg" },
  SportGlasses_Green: { file: "Athletic Sunglasses Green.png", wiki: "wiki.gg" },
  SportGlasses_Orange: { file: "Athletic Sunglasses Orange.png", wiki: "wiki.gg" },
  Sweater_ChristmasBlue: { file: "Sweater ChristmasBlue.png", wiki: "wiki.gg" },
  Sweater_ChristmasGreen: { file: "Sweater ChristmasGreen.png", wiki: "wiki.gg" },
  Sweater_ChristmasRed: { file: "Sweater ChristmasRed.png", wiki: "wiki.gg" },
  TTSKOPants: { file: "TTSKOtrou.png", wiki: "wiki.gg" },
  TTsKOJacket_Camo: { file: "TTsKOJacket Camo.png", wiki: "wiki.gg" },
  TacticalGloves_Beige: { file: "TacticalGloves Beige.png", wiki: "wiki.gg" },
  TacticalGloves_Black: { file: "TacticalGloves Black.png", wiki: "wiki.gg" },
  TacticalGloves_Green: { file: "TacticalGloves Green.png", wiki: "wiki.gg" },
  TacticalGoggles: { file: "TacticalGoggles.png", wiki: "wiki.gg" },
  TacticalShirt_Black: { file: "https://static.wikia.nocookie.net/dayz_gamepedia/images/4/47/Item_Tactical_Shirt_BLACK.png/revision/latest/scale-to-width-down/1000?cb=20180620231903", wiki: "supplied" },
  TacticalShirt_Grey: { file: "TacticalShirtGrey.png", wiki: "wiki.gg" },
  TacticalShirt_Olive: { file: "Tactical_Shirt_Olive.png", wiki: "wiki.gg" },
  TacticalShirt_Tan: { file: "TacticalShirtTan.png", wiki: "wiki.gg" },
  ThickFramesGlasses: { file: "Glasses with thick frames.png", wiki: "wiki.gg" },
  ThinFramesGlasses: { file: "ThinGlass01.png", wiki: "wiki.gg" },
  TortillaBag: { file: "SPOSN Tortilla Backpack.png", wiki: "wiki.gg" },
  TortillaBag_Desert: { file: "", wiki: "local" },
  TortillaBag_Winter: { file: "TortillaBag Winter.png", wiki: "wiki.gg" },
  TraditionalBoots_Beige: { file: "TraditionalBoots Beige.png", wiki: "wiki.gg" },
  TraditionalBoots_DarkBrown: { file: "TraditionalBoots DarkBrown.png", wiki: "wiki.gg" },
  USMCJacket_Desert: { file: "USMCJacket Desert.png", wiki: "wiki.gg" },
  USMCJacket_Woodland: { file: "USMCJacket Woodland.png", wiki: "wiki.gg" },
  USMCPants_Desert: { file: "USMCPants Desert.png", wiki: "wiki.gg" },
  USMCPants_Woodland: { file: "USMCPants Woodland.png", wiki: "wiki.gg" },
  WinterMilitaryCoat_Brown: { file: "WinterMilitaryCoat Brown.png", wiki: "wiki.gg" },
  WinterMilitaryCoat_DarkGrey: { file: "WinterMilitaryCoat DarkGrey.png", wiki: "wiki.gg" },
  WinterMilitaryCoat_Grey: { file: "WinterMilitaryCoat Grey.png", wiki: "wiki.gg" },
  WitchHat: { file: "WitchHat.png", wiki: "wiki.gg" },
  WitchHood_Black: { file: "WitchHood Black.png", wiki: "wiki.gg" },
  WitchHood_Brown: { file: "WitchHood Brown.png", wiki: "wiki.gg" },
  WitchHood_Red: { file: "WitchHood Red.png", wiki: "wiki.gg" },
  WorkingGloves_Beige: { file: "WorkingGloves Beige.png", wiki: "wiki.gg" },
  WorkingGloves_Black: { file: "WorkingGloves Black.png", wiki: "wiki.gg" },
  WorkingGloves_Brown: { file: "WorkingGloves Brown.png", wiki: "wiki.gg" },
  WorkingGloves_Yellow: { file: "WorkingGloves Yellow.png", wiki: "wiki.gg" },
};

/**
 * What the wiki calls this item's image, or undefined when we have no source.
 *
 * ⚠️ Returns undefined rather than throwing, UNLIKE flag-images.ts. For a flag
 * a miss is a bug; for an item "no art yet" is a legitimate state the picker
 * renders as a placeholder tile.
 */
export function wikiFileFor(className: string): { file: string; wiki: string } | undefined {
  return WIKI_FILENAME[className];
}

/**
 * Where we serve it, relative to `public/`.
 *
 * ⚠️ Named after OUR class name, never the wiki's, so the wikis' naming stops
 * here at fetch time rather than travelling into the picker or the bot. Same
 * discipline as flagImagePath.
 */
export function itemImagePath(className: string): string {
  return `items/${className}.webp`;
}
