import { describe, it, expect } from "vitest";
import { existsSync, readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import sharp from "sharp";
import { CLAIMABLE_FLAGS } from "@factions/domain";
import { FLAG_THUMB_EDGE, flagThumbPath } from "../src/flag-images";
import { pathIsPublic } from "../lib/auth/gate";

const WEB = join(import.meta.dirname, "..");
const THUMBS = join(WEB, "public", "flags", "thumb");

/**
 * H5: every list drew the 256×128 PNG (~50KB, 1.7MB for the pool) at 24–48px.
 * The thumbnails are generated by scripts/build-flag-thumbs.ts from the
 * committed PNGs and committed. ⚠️ A texture added to CLAIMABLE_FLAGS without
 * re-running it is a broken image in every list, and nothing else notices —
 * the same two-statements-of-one-fact shape as flag-assets.test.ts.
 */
describe("flag thumbnails match CLAIMABLE_FLAGS", () => {
  const files = existsSync(THUMBS) ? readdirSync(THUMBS).filter((f) => f.endsWith(".webp")) : [];

  it("⚠️ every claimable flag has a thumbnail", () => {
    expect(CLAIMABLE_FLAGS.filter((t) => !files.includes(`${t}.webp`))).toEqual([]);
  });

  it("every thumbnail belongs to a claimable flag", () => {
    expect(files.filter((f) => !CLAIMABLE_FLAGS.includes(f.replace(/\.webp$/u, "")))).toEqual([]);
  });

  it("is FLAG_THUMB_EDGE on its long edge, landscape, and small", async () => {
    for (const f of files) {
      const { width = 0, height = 0, format } = await sharp(join(THUMBS, f)).metadata();
      expect(format, f).toBe("webp");
      expect(Math.max(width, height), `${f} long edge`).toBe(FLAG_THUMB_EDGE);
      expect(width, `${f} landscape`).toBeGreaterThan(height);
      expect(statSync(join(THUMBS, f)).size, `${f} bytes`).toBeLessThan(8_000);
    }
  });

  it("⚠️ is served to an anonymous visitor — public/ files are gated unless listed", () => {
    expect(flagThumbPath("Flag_Wolf")).toBe("flags/thumb/Flag_Wolf.webp");
    expect(pathIsPublic(`/${flagThumbPath("Flag_Wolf")}`)).toBe(true);
  });
});

/**
 * Only the heroes draw the full PNG (a 256–416px flag); every list draws the
 * thumbnail, lazily. The claim page is the FORMS plan's and keeps its PNG.
 */
describe("which pages use which flag", () => {
  const FULL_SIZE = new Set([
    "app/(site)/clans/[tag]/page.tsx",
    "app/(site)/players/[gamertag]/page.tsx",
    "app/components/own-clan-hero.tsx",
  ]);
  const sources = (readdirSync(join(WEB, "app"), { recursive: true, encoding: "utf8" }) as string[])
    .filter((f) => f.endsWith(".tsx"))
    .map((f) => `app/${f.split("\\").join("/")}`)
    .map((rel) => [rel, readFileSync(join(WEB, rel), "utf8")] as const);

  it("no list draws the full-size PNG", () => {
    const offenders = sources.filter(([rel, text]) => !FULL_SIZE.has(rel) && text.includes("flagImagePath(")).map(([rel]) => rel);
    expect(offenders).toEqual([]);
  });

  it("⚠️ every thumbnail <img> is loading=\"lazy\"", () => {
    const eager = sources.flatMap(([rel, text]) =>
      [...text.matchAll(/<img\b[^>]*flagThumbPath\([^>]*>/gu)].filter((m) => !m[0].includes('loading="lazy"')).map(() => rel));
    expect(eager).toEqual([]);
  });
});
